-- ============================================================
-- PR507A owner-authored private encounter curation metadata
-- ============================================================

create or replace function public.persona_encounter_private_session_tags_valid(tags text[])
returns boolean
language sql
immutable
as $$
  select tags is not null
    and cardinality(tags) <= 12
    and not exists (
      select 1
      from unnest(tags) as tag
      where tag is null
        or char_length(btrim(tag)) not between 1 and 40
    );
$$;

alter table public.persona_encounter_private_sessions
  add column if not exists owner_title text,
  add column if not exists owner_summary text,
  add column if not exists owner_tags text[] not null default '{}'::text[],
  add column if not exists publication_candidate boolean not null default false,
  add column if not exists curation_schema text not null default 'station.persona_encounter.private_session_curation.v1';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'persona_encounter_private_sessions_owner_title_length_check'
  ) then
    alter table public.persona_encounter_private_sessions
      add constraint persona_encounter_private_sessions_owner_title_length_check
      check (owner_title is null or char_length(btrim(owner_title)) between 1 and 120);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'persona_encounter_private_sessions_owner_summary_length_check'
  ) then
    alter table public.persona_encounter_private_sessions
      add constraint persona_encounter_private_sessions_owner_summary_length_check
      check (owner_summary is null or char_length(btrim(owner_summary)) between 1 and 800);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'persona_encounter_private_sessions_owner_tags_check'
  ) then
    alter table public.persona_encounter_private_sessions
      add constraint persona_encounter_private_sessions_owner_tags_check
      check (public.persona_encounter_private_session_tags_valid(owner_tags));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'persona_encounter_private_sessions_curation_schema_check'
  ) then
    alter table public.persona_encounter_private_sessions
      add constraint persona_encounter_private_sessions_curation_schema_check
      check (curation_schema = 'station.persona_encounter.private_session_curation.v1');
  end if;
end $$;

comment on column public.persona_encounter_private_sessions.owner_title is
  'Owner-authored private title for local curation only. Not public, shareable, moderated, or cross-owner consent metadata.';

comment on column public.persona_encounter_private_sessions.owner_summary is
  'Owner-authored private note or summary for local curation only. Not generated by provider calls.';

comment on column public.persona_encounter_private_sessions.owner_tags is
  'Owner-authored private tags for local curation only.';

comment on column public.persona_encounter_private_sessions.publication_candidate is
  'Private owner planning flag only. Does not create publication, public visibility, sharing, moderation, or cross-owner consent.';

comment on column public.persona_encounter_private_sessions.curation_schema is
  'Schema marker for owner-authored private encounter curation metadata.';
