import { Router } from "express";
import { z } from "zod";
import type { Database } from "@station/db";
import type { InstitutionSpaceDetail } from "@station/types";
import { getSupabaseAdmin } from "../lib/supabase";
import { requireAuth } from "../middleware/require-auth";

type InstitutionRow=Database["public"]["Tables"]["institutions"]["Row"];
type SpaceRow=Database["public"]["Tables"]["institution_spaces"]["Row"];
const slug=z.string().min(3).max(80).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
const snapshot=z.object({markText:z.string().trim().min(1).max(4).regex(/^[A-Za-z0-9&+]+$/),headline:z.string().trim().min(1).max(160),about:z.string().trim().min(1).max(3000),accentKey:z.enum(["cobalt","coral","forest","gold"])}).strict();
const edit=snapshot.extend({expectedVersion:z.number().int().positive()}).strict();
const transition=z.object({expectedVersion:z.number().int().positive()}).strict();
const NOT_FOUND={error:"Institution Space not found.",code:"institution_space_not_found"} as const;
const READ_FAILED={error:"Could not load Institution Space.",code:"institution_space_load_failed"} as const;
const WRITE_FAILED={error:"Could not update Institution Space.",code:"institution_space_update_failed"} as const;
export const institutionSpacesRouter=Router();
institutionSpacesRouter.use("/institutions/:institutionSlug/space",requireAuth);
institutionSpacesRouter.use("/institutions/:institutionSlug/space",(_req,res,next)=>{res.set("Cache-Control","private, no-store");next()});
function first<T>(value:T|T[]|null){return Array.isArray(value)?value[0]??null:value}
async function institutionFor(value:string){if(!slug.safeParse(value).success)return null;const {data,error}=await getSupabaseAdmin().from("institutions").select("*").eq("slug",value).maybeSingle();if(error)throw new Error("institution read");return data as InstitutionRow|null}
async function roleFor(institution:InstitutionRow,userId:string){if(institution.owner_user_id===userId)return "institution_owner" as const;const {data,error}=await getSupabaseAdmin().from("institution_members").select("id").eq("institution_id",institution.id).eq("user_id",userId).eq("role","member").eq("status","active").maybeSingle();if(error)throw new Error("membership read");return data?"institution_member" as const:null}
async function actorLabel(userId:string){const {data,error}=await getSupabaseAdmin().from("profiles").select("username, display_name").eq("id",userId).maybeSingle();if(error||!data)throw new Error("profile read");return String(data.display_name||data.username).trim().slice(0,120)}
async function spaceFor(institutionId:string){const {data,error}=await getSupabaseAdmin().from("institution_spaces").select("*").eq("institution_id",institutionId).maybeSingle();if(error)throw new Error("space read");return data as SpaceRow|null}
function serialize(row:SpaceRow,institution:InstitutionRow,role:"institution_owner"|"institution_member"):InstitutionSpaceDetail{const owner=role==="institution_owner";return{markText:row.mark_text,headline:row.headline,about:row.about,accentKey:row.accent_key,status:row.status,version:row.version,creatorLabel:row.creator_label,lastEditorLabel:row.last_editor_label,createdAt:row.created_at,updatedAt:row.updated_at,publishedAt:row.published_at,publicHref:row.status==="published"&&institution.verification_status==="verified"&&institution.public_status==="public"?`/institutions/${encodeURIComponent(institution.slug)}`:null,institution:{name:institution.name,slug:institution.slug,href:institution.verification_status==="verified"&&institution.public_status==="public"?`/institutions/${encodeURIComponent(institution.slug)}`:null},access:{role,readOnly:!owner,canPublish:owner&&row.status==="draft",canUnpublish:owner&&row.status==="published"}}}

institutionSpacesRouter.get("/institutions/:institutionSlug/space",async(req,res)=>{try{const institution=await institutionFor(req.params.institutionSlug);if(!institution)return res.status(404).json(NOT_FOUND);const role=await roleFor(institution,req.user!.id);if(!role)return res.status(404).json(NOT_FOUND);const space=await spaceFor(institution.id);return res.json({space:space?serialize(space,institution,role):null,institution:{name:institution.name,slug:institution.slug,access:{role,readOnly:role!=="institution_owner"}}})}catch{return res.status(500).json(READ_FAILED)}});
institutionSpacesRouter.post("/institutions/:institutionSlug/space",async(req,res)=>{const parsed=snapshot.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Enter valid Institution Space details.",code:"institution_space_details_invalid"});try{const institution=await institutionFor(req.params.institutionSlug);if(!institution||institution.owner_user_id!==req.user!.id)return res.status(404).json(NOT_FOUND);const {data,error}=await getSupabaseAdmin().rpc("create_institution_space_v1",{p_institution_id:institution.id,p_actor_user_id:req.user!.id,p_actor_label:await actorLabel(req.user!.id),p_mark_text:parsed.data.markText,p_headline:parsed.data.headline,p_about:parsed.data.about,p_accent_key:parsed.data.accentKey});if(error?.code==="23505")return res.status(409).json({error:"This Institution already has a Space.",code:"institution_space_exists"});if(error||!data)return res.status(500).json(WRITE_FAILED);return res.status(201).json({space:serialize(data as SpaceRow,institution,"institution_owner")})}catch{return res.status(500).json(WRITE_FAILED)}});
institutionSpacesRouter.patch("/institutions/:institutionSlug/space",async(req,res)=>{const parsed=edit.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Enter a complete Institution Space snapshot.",code:"institution_space_snapshot_invalid"});try{const institution=await institutionFor(req.params.institutionSlug);if(!institution||institution.owner_user_id!==req.user!.id)return res.status(404).json(NOT_FOUND);const space=await spaceFor(institution.id);if(!space)return res.status(404).json(NOT_FOUND);const {data,error}=await getSupabaseAdmin().rpc("edit_institution_space_v1",{p_space_id:space.id,p_actor_user_id:req.user!.id,p_actor_label:await actorLabel(req.user!.id),p_expected_version:parsed.data.expectedVersion,p_mark_text:parsed.data.markText,p_headline:parsed.data.headline,p_about:parsed.data.about,p_accent_key:parsed.data.accentKey});if(error)return res.status(500).json(WRITE_FAILED);const result=first(data);if(result?.outcome==="conflict")return res.status(409).json({error:"This Institution Space changed. Reload before saving.",code:"institution_space_version_conflict",currentVersion:result.new_version});if(result?.outcome!=="edited")return res.status(404).json(NOT_FOUND);return res.json({status:"edited",version:result.new_version})}catch{return res.status(500).json(WRITE_FAILED)}});
async function change(req:any,res:any,action:"publish"|"unpublish"){const parsed=transition.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Use the current Institution Space version.",code:"institution_space_version_invalid"});try{const institution=await institutionFor(req.params.institutionSlug);if(!institution||institution.owner_user_id!==req.user!.id)return res.status(404).json(NOT_FOUND);const space=await spaceFor(institution.id);if(!space)return res.status(404).json(NOT_FOUND);const {data,error}=await getSupabaseAdmin().rpc("transition_institution_space_v1",{p_space_id:space.id,p_actor_user_id:req.user!.id,p_expected_version:parsed.data.expectedVersion,p_action:action});if(error)return res.status(500).json(WRITE_FAILED);const result=first(data);if(result?.outcome==="conflict")return res.status(409).json({error:"This Institution Space changed. Reload before continuing.",code:"institution_space_version_conflict",currentVersion:result.new_version});if(result?.outcome!==action+"ed"&&!(action==="publish"&&result?.outcome==="published"))return res.status(404).json(NOT_FOUND);return res.json({status:result.outcome,version:result.new_version})}catch{return res.status(500).json(WRITE_FAILED)}}
institutionSpacesRouter.post("/institutions/:institutionSlug/space/publish",(req,res)=>change(req,res,"publish"));
institutionSpacesRouter.post("/institutions/:institutionSlug/space/unpublish",(req,res)=>change(req,res,"unpublish"));
