"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import type { InstitutionSpaceAccentKey, InstitutionSpaceDetail } from "@station/types";
import { ApiRequestError, apiGet, apiPatch, apiPost } from "@/lib/api-client";
import { getSession } from "@/lib/auth";
import { institutionActivityPath, institutionCommunityPath, institutionSpacePath, institutionTeamPath } from "@/lib/institutions";

const accents:{key:InstitutionSpaceAccentKey;label:string}[]=[{key:"cobalt",label:"Cobalt"},{key:"coral",label:"Coral"},{key:"forest",label:"Forest"},{key:"gold",label:"Gold"}];
type Readback={space:InstitutionSpaceDetail|null;institution:{name:string;slug:string;access:{role:"institution_owner"|"institution_member";readOnly:boolean}}};
export default function InstitutionSpaceWorkspace(){
  const params=useParams<{slug:string}>();const slug=decodeURIComponent(String(params.slug??""));
  const [data,setData]=useState<Readback|null>(null),[token,setToken]=useState<string|null>(null),[markText,setMark]=useState("ST"),[headline,setHeadline]=useState(""),[about,setAbout]=useState(""),[accentKey,setAccent]=useState<InstitutionSpaceAccentKey>("cobalt"),[pending,setPending]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
  const load=useCallback(async(t:string)=>{const response=await apiGet<Readback>(institutionSpacePath(slug),t);setData(response);if(response.space){setMark(response.space.markText);setHeadline(response.space.headline);setAbout(response.space.about);setAccent(response.space.accentKey)}},[slug]);
  useEffect(()=>{let cancelled=false;getSession().then(async session=>{if(!session||cancelled)return;setToken(session.access_token);try{await load(session.access_token)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Institution Space not found.")}});return()=>{cancelled=true}},[load]);
  const owner=data?.institution.access.role==="institution_owner",space=data?.space;
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!token||!owner)return;setPending("save");setError(null);setMessage(null);try{const body={markText,headline,about,accentKey};if(space)await apiPatch(institutionSpacePath(slug),{...body,expectedVersion:space.version},token);else await apiPost(institutionSpacePath(slug),body,token);await load(token);setMessage(space?"Institution Space draft saved.":"Institution Space draft created.")}catch(e){setError(e instanceof ApiRequestError&&e.status===409?"This Institution Space changed. Reload before saving.":e instanceof Error?e.message:"Could not save this Institution Space.")}finally{setPending(null)}}
  async function change(action:"publish"|"unpublish"){if(!token||!space||!owner)return;setPending(action);setError(null);setMessage(null);try{await apiPost(`${institutionSpacePath(slug)}/${action}`,{expectedVersion:space.version},token);await load(token);setMessage(action==="publish"?"Institution Space published.":"Institution Space returned to private draft.")}catch(e){setError(e instanceof Error?e.message:`Could not ${action} this Institution Space.`)}finally{setPending(null)}}
  return <main className="station-page institution-page"><div className="station-page-inner station-page-inner-narrow institution-stack">
    <header className="station-page-header"><div><div className="station-eyebrow">Institutional Space workspace</div><h1 className="station-page-title institution-wrap">{data?.institution.name??"Institutional Space"}</h1><p className="station-page-lede">{owner?"Owner configuration":"Active member / read-only configuration"}</p></div><div className="station-action-row"><Link className="station-muted-button" href={institutionTeamPath(slug)}>Back to team</Link>{owner?<Link className="station-muted-button" href={institutionActivityPath(slug)}>Activity</Link>:null}</div></header>
    {error?<div className="station-notice" data-tone="error">{error}</div>:null}{message?<div className="station-notice" data-tone="success">{message}</div>:null}{!data&&!error?<div className="station-notice">Loading Institution Space...</div>:null}
    {data?<><section className={`institution-space-preview institution-accent-${accentKey}`}><div className="institution-space-mark">{markText||"ST"}</div><div><span className="public-institution-verified">Verified Institution</span><h2>{headline||"Authored Institution headline"}</h2><p>{about||"The Institution owner can author a bounded public introduction here."}</p></div></section>
    <form className="station-panel institution-stack" onSubmit={save}><div className="institution-status-row"><span className="station-status-pill">{space?.status??"not created"}</span>{space?<span className="station-status-pill">Version {space.version}</span>:null}<span className="station-status-pill">{owner?"Owner":"Member / read-only"}</span></div>{space?<p>Created by {space.creatorLabel}. Last edited by {space.lastEditorLabel}.</p>:null}
      <label className="institution-field"><span>Mark</span><input className="input" value={markText} onChange={e=>setMark(e.target.value.toUpperCase().replace(/[^A-Z0-9&+]/g,"").slice(0,4))} maxLength={4} disabled={!owner||space?.status==="published"} required /></label>
      <label className="institution-field"><span>Headline</span><input className="input" value={headline} onChange={e=>setHeadline(e.target.value)} maxLength={160} disabled={!owner||space?.status==="published"} required /></label>
      <label className="institution-field"><span>About</span><textarea className="input" value={about} onChange={e=>setAbout(e.target.value)} rows={8} maxLength={3000} disabled={!owner||space?.status==="published"} required /></label>
      <fieldset className="institution-accent-field" disabled={!owner||space?.status==="published"}><legend>Accent</legend><div className="institution-accent-options">{accents.map(accent=><label key={accent.key} className="institution-accent-option"><input type="radio" name="accent" value={accent.key} checked={accentKey===accent.key} onChange={()=>setAccent(accent.key)} /><span className={`institution-accent-swatch institution-accent-${accent.key}`} aria-hidden="true" />{accent.label}</label>)}</div></fieldset>
      <div className="station-action-row">{owner&&space?.status!=="published"?<button className="station-link-button" type="submit" disabled={pending!==null}>{pending==="save"?"Saving...":space?"Save draft":"Create draft"}</button>:null}{space?.access.canPublish?<button className="station-link-button" type="button" disabled={pending!==null} onClick={()=>change("publish")}>{pending==="publish"?"Publishing...":"Publish"}</button>:null}{space?.access.canUnpublish?<button className="station-muted-button" type="button" disabled={pending!==null} onClick={()=>change("unpublish")}>{pending==="unpublish"?"Unpublishing...":"Unpublish"}</button>:null}{space?.publicHref?<Link className="station-muted-button" href={space.publicHref}>Open public page</Link>:null}<Link className="station-muted-button" href={institutionCommunityPath(slug)}>Institution community</Link></div>
    </form></>:null}
  </div></main>
}
